model_id: "--model-id anthropic.claude-3-opus-20240229-v1:0"
region: "--region us-west-2"
popular_science_prompt:
  basic: 'Based on the following reference materials, please share the most common hacking techniques in a very easy-to-understand way. The target audience is beginners in information.'
  professional: 'Based on the following reference materials, please describe in detail the most common hacker attack methods in a specific and clear manner. The target audience is information security personnel.'